version: "3.9"

services:
  balance_alembic:
    image: balance_alembic:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run migrations' && \
      alembic stamp head --purge && \
      alembic revision --autogenerate -m "Migrations" && \
      alembic upgrade head"
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      balance_database:
        condition: service_healthy
