version: "3.9"

services:
  balance_backend:
    image: balance_backend:latest
    build:
      context: ${PWD}/balance
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Balance Backend' && \
      python main.py"
    volumes:
      - ${PWD}/balance/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      balance_database:
        condition: service_healthy
    expose:
      - ${BALANCE_PORT}
    restart: unless-stopped
